services:
  - name: school-service
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: ohio
    healthCheckPath: /
    autoDeploy: true
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/schoolservice-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-mysql-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: my-mysql-db
          property: username
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: my-mysql-db
          property: password

databases:
  - name: my-mysql-db
    type: mysql
    plan: free
    region: oregon
    databaseName: mydatabase
    user: myuser
    password: mypassword
